<?php

/*
 * Copies FrameTrail's JSON Schemas into server/lib/frametrail/schemas.json, for
 * the PHP validator: the server part runs inside a FrameTrail installation,
 * whose build carries the schemas only inside its JavaScript bundle. The copy
 * is the one the player loads (FrameTrailSchemas.js: every schema of schemas/
 * without titles and descriptions), from a FrameTrail working copy:
 *
 *     php scripts/vendor-schemas.php                   # ../frametrail, or FRAMETRAIL_DIR
 *     php scripts/vendor-schemas.php --frametrail=<dir>
 *
 * Run it when the add-on moves to a FrameTrail release with other schemas;
 * php tests/run-php.php fails while the copy differs from the working copy's.
 */

/**
 * The schemas of a FrameTrail working copy, as the JSON text of a list with
 * one schema per line.
 *
 * @method ftConversationalUiFrameTrailSchemasText
 * @param {String} $frametrail the working copy
 * @return String
 * @throws Exception when the working copy has no FrameTrailSchemas.js
 */
function ftConversationalUiFrameTrailSchemasText($frametrail) {

    $file = $frametrail . "/src/_shared/frametrail-core/schema/FrameTrailSchemas.js";

    if (!is_file($file)) {
        throw new Exception("No FrameTrail working copy (1.4.1 or later) at " . $frametrail . "; set FRAMETRAIL_DIR or pass --frametrail=<dir>");
    }

    // Generated by FrameTrail's scripts/bundle-schemas.mjs: "(function(schemas) {…})([\n<one schema per line>\n]);"
    $source = str_replace("\r\n", "\n", file_get_contents($file));
    $start  = strpos($source, "})([\n");
    $end    = strrpos($source, "\n]);");

    if ($start === false || $end === false || $end < $start) {
        throw new Exception("Unexpected form of " . $file);
    }

    $text = "[\n" . substr($source, $start + 5, $end - $start - 5) . "\n]\n";

    if (!is_array(json_decode($text))) {
        throw new Exception("No list of schemas in " . $file);
    }

    return $text;

}

// The FrameTrail working copy named by --frametrail=, FRAMETRAIL_DIR, or ../frametrail.
function ftConversationalUiFrameTrailDir($argv, $root) {
    foreach ($argv as $arg) {
        if (strpos($arg, "--frametrail=") === 0) { return substr($arg, strlen("--frametrail=")); }
    }
    $env = getenv("FRAMETRAIL_DIR");
    if ($env !== false && $env !== "") {
        return ($env[0] === "/") ? $env : $root . "/" . $env;
    }
    return dirname($root) . "/frametrail";
}


if (PHP_SAPI === "cli" && isset($argv[0]) && realpath($argv[0]) === __FILE__) {

    $root   = dirname(__DIR__);
    $target = $root . "/server/lib/frametrail/schemas.json";

    try {
        $text = ftConversationalUiFrameTrailSchemasText(ftConversationalUiFrameTrailDir($argv, $root));
    } catch (Exception $e) {
        fwrite(STDERR, $e->getMessage() . "\n");
        exit(1);
    }

    file_put_contents($target, $text);

    echo "Wrote " . substr($target, strlen($root) + 1) . " (" . count(json_decode($text)) . " schemas)\n";

}
